S4 us9/footer
WildCodeSchool/2023-09-js-tlse-p2-cocktail-atom pull request #10
Opened 2023-11-14 16:44 UTC by Delmastan

2023-11-14 19:14 UTC, QuentinVay approved these changes

2023-11-15 08:35 UTC, ArthurHtbk requested changes

2023-11-15 08:35 UTC, ArthurHtbk commented on frontend/src/components/Footer.jsx
> +        <h3>Alcohol to be consumed in moderation</h3>
Alcohol is to be consumed in moderation

2023-11-15 08:36 UTC, ArthurHtbk approved these changes

2023-11-15 08:36 UTC, merged